# Generated by Django 5.1.6 on 2025-03-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userid', models.CharField(db_column='userID', max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=100)),
                ('lastname', models.CharField(db_column='lastName', max_length=100)),
                ('userpass', models.CharField(blank=True, db_column='userPass', max_length=64, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcementid', models.AutoField(db_column='announcementID', primary_key=True, serialize=False)),
                ('announcement', models.TextField(blank=True, null=True)),
                ('announcementtime', models.DateTimeField(blank=True, db_column='announcementTime', null=True)),
            ],
            options={
                'db_table': 'announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('breakid', models.AutoField(db_column='breakID', primary_key=True, serialize=False)),
                ('breakstart', models.DateTimeField(blank=True, db_column='breakStart', null=True)),
                ('breakend', models.DateTimeField(blank=True, db_column='breakEnd', null=True)),
            ],
            options={
                'db_table': 'break',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.CharField(db_column='companyID', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shifttime',
            fields=[
                ('shiftid', models.AutoField(db_column='shiftID', primary_key=True, serialize=False)),
                ('clockin', models.DateTimeField(blank=True, db_column='clockIn', null=True)),
                ('clockout', models.DateTimeField(blank=True, db_column='clockOut', null=True)),
                ('breakduration', models.TimeField(blank=True, db_column='breakDuration', null=True)),
            ],
            options={
                'db_table': 'shifttime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersalary', models.DecimalField(blank=True, db_column='userSalary', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'employed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensedate', models.DateField(db_column='expenseDate')),
                ('expense', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'notices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roletable',
            fields=[
                ('userrole', models.CharField(db_column='userRole', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roletable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('scheduleid', models.AutoField(db_column='scheduleID', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('shiftid', models.OneToOneField(db_column='shiftID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.shifttime')),
                ('shiftcompensation', models.DecimalField(blank=True, db_column='shiftCompensation', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'compensation',
                'managed': False,
            },
        ),
    ]
